### ISSUE TITLE
[Flow EVM] Integration test improvements 

### ISSUE THREAD

**Issue by franklywatson** [onflow/flow-go#4962] opened 2023-11-08 18:37 UTC
## Problem Definition

	- add assertions for results / execution state changes
	- add test to check the location access limit to internal contract
	- deposit/withdraw non-zero amounts
	- deploy proper contract
	- Refactor test utils from continuation-passing style to simple returns

**Comment by j1010001** [comment] 2024-01-16 20:31
duplicate of #5228

**Closed by j1010001** 2024-01-16 20:31 UTC
Labels: Flow EVM
