### ISSUE TITLE
GetEventsForHeightRange not returning events, only other properties

### ISSUE THREAD

**Issue by dougg0k** [onflow/flow-go#1770] opened 2021-12-13 21:46 UTC
Hi,

I have the problem that is in the title, pretty much been testing with `TopShot` events, in candidate and mainnet sporks, I get the same result. Legacy candidate sporks doesnt have `block_timestamp`, but both are not returning events. 
```
{
    "block_id": "NrbRbAtKPAGPbtmqptRL+V1iXhcTjjxaVe2oNT4Nwwc=",
    "block_height": "8743208",
    "block_timestamp": {
      "seconds": "1605316068",
      "nanos": 589451753
    }
  }
```

`type: A.0b2a3299cc857e29.TopShot.MomentMinted` - `start_height: 8742959` - `end_height: 8742959 + 249`

```
syntax = "proto3";

package flow.access;

service AccessAPI {
  rpc GetEventsForHeightRange(GetEventsForHeightRangeRequest) returns (GetEventsForHeightRangeResponse);
}

message GetEventsForHeightRangeRequest {
  string type = 1;
  uint64 start_height = 2;
  uint64 end_height = 3;
}

message GetEventsForHeightRangeResponse {
  message Result {
    bytes block_id = 1;
    uint64 block_height = 2;
    repeated Event events = 3;
    Timestamp block_timestamp = 4;
  }
  repeated Result results = 1;
}

message Event {
  string type = 1;
  bytes transaction_id = 2;
  uint32 transaction_index = 3;
  uint32 event_index = 4;
  bytes payload = 5;
}

message Timestamp {
  int64 seconds = 1;
  int32 nanos = 2;
}
```
It complains if any of the 3 parameters are missing, but if I put a random type parameter, it returns block either way, isn't suppose to only return that which is a part of that type? 

If not, has anything changed from that pattern used starting with `A.`?

**Comment by dougg0k** [comment] 2021-12-16 13:34
Not sure if intended, but all blocks are returned given the range specifified, the difference is that if the block doesnt contain the type specified, it returns no events or empty array of events.

**Comment by peterargue** [comment] 2023-09-21 22:50
Sorry for the extremely late response! This is the expected behavior, as it ensure the caller knows the exact range searched (since it may be slightly different from the requested range).

Closing this since it's so old, but feel free to reopen if it's not resolved

**Closed by peterargue** 2023-09-21 22:50 UTC
