### ISSUE TITLE
Access node unreachable

### ISSUE THREAD

**Issue by Luze26** [onflow/flow-go#4016] opened 2023-03-08 17:12 UTC
## 🐞 Bug Report

Access node unreachable.

## What is the severity of this bug?

**Critical:** It causes many issues when using subcribe or onceSealed from FCL to execute transactions correctly. It can happen with other calls to the API too.

## Reproduction steps

Make API calls, some will randomly fail. Saw an increase number of this errors since yeterday.

## Expected behaviour

To be able to access the access node or at least have some retry mechanism in these cases if it's not already the case.

## Additional context

```
2023-03-08T16:00:54.561Z
ERROR	Access Node Error
============================

The provided access node https://rest-mainnet.onflow.org does not appear to be a valid REST/HTTP access node.
Please verify that you are not unintentionally using a GRPC access node.
See more here: https://docs.onflow.org/fcl/reference/sdk-guidelines/#connect

============================
```

```
2023-03-08T16:00:54.562Z
ERROR	=== SAD PANDA ===

 HTTPRequestError [HTTP Request Error]: 
      HTTP Request Error: An error occurred when interacting with the Access API.
      error=request to https://rest-mainnet.onflow.org/v1/accounts/ff8d2bbed8164db0?block_height=sealed&expand=contracts,keys failed, reason: connect ETIMEDOUT 104.18.29.209:443
      hostname=https://rest-mainnet.onflow.org
      path=/v1/accounts/ff8d2bbed8164db0?block_height=sealed&expand=contracts,keys
      method=GET
      
      
      
      
    
    at _callee2$ (/var/task/node_modules/@onflow/transport-http/dist/sdk-send-http.js:249:33)
    at tryCatch (/var/task/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/var/task/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/var/task/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/var/task/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/var/task/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: undefined,
  errorMessage: 'request to https://rest-mainnet.onflow.org/v1/accounts/ff8d2bbed8164db0?block_height=sealed&expand=contracts,keys failed, reason: connect ETIMEDOUT 104.18.29.209:443'
} 
```

**Comment by franklywatson** [comment] 2023-03-08 19:14
Thanks for the report., we're investigating currently

**Comment by Kay-Zee** [comment] 2023-03-08 19:46
> least have some retry mechanism in these cases if it's not already the case.

If you are specifically interested in the retry mechanism, that would be in the FCL library here: https://github.com/onflow/fcl-js

**Comment by franklywatson** [comment] 2023-03-08 21:04
The root cause was found to be a client side timeout which wasn't well handled in https://github.com/onflow/fcl-js/blob/master/packages/transport-http/src/http-request.js#L58. Closing this

**Closed by franklywatson** 2023-03-08 21:04 UTC

**Comment by ph0ph0** [comment] 2023-03-09 09:42
@franklywatson would it be worth us switching to gRPC api instead of REST api, or would we still experience this issue with gRPC?

**Comment by franklywatson** [comment] 2023-03-09 15:58
This issue was closed because it's not the right repo and the fix will likely not yet be released. To my undertstanding FCL only uses REST, not sure if switching would be an option
