### ISSUE TITLE
Race condition in getEventsAtBlockHeightRange

### ISSUE THREAD

**Issue by NtTestAlert** [onflow/flow-go#3873] opened 2023-01-27 11:18 UTC
### The problem

There is a potential race condition in `getEventsAtBlockHeightRange` RPC call, for blocks near to the latest sealed block.
This might be a case of "it's a feature not a bug", as the results are not incorrect, just inconsistent over time, but it can cause consumers to unknowingly skip events from entire blocks, which could be hard to debug.

Because the access node acts as a load balancer, what one node believes to be latestSealedBlock, might not be what another does, due to sync delays.
In order to create inputs for `getEventsAtBlockHeightRange` we need to know the latestSealedBlock to use as inputs.
If we only need to load one block, and startHeight falls into the race condition case where the node queried for events is behind on blocks, it will throw an error, which will usually cause our consumer system to correct itself.
But if our consumer is behind, and we are loading more than one block, there is a rare case where the call will return inconsistent data, without any way to tell it.

Case 1 - normal operation
getBlock(true).height returns 10
getEventsAtBlockHeightRange 9 - 10 returns events from block 9 and 10 because the sub-node believes 10 is sealed

Case 2 - race condition 1 non-critical
getBlock(true).height returns 10
getEventsAtBlockHeightRange 9 - 10 throws error, because the sub-node believes 8 is max sealed, and our startRange is lower

Case 3 - race condition 2 critical
getBlock(true).height returns 10
getEventsAtBlockHeightRange 9 - 10 returns events from block 9 only, because the sub-node believes 9 is max sealed, and our startRange satisfies it

Case 3 is a silent "error" that is not detectable by the consumer, and may lead to inconsistent state. It can be worked around by "mistrusting" the results for block ranges that are close to sealed head, either by treating startHeight as the new verified "latest polled height", as it is checked by the server, or using some other heuristic, and re-querying other blocks.

It is a very rare case, that only happened 2-3 times this past year, but it was difficult to debug properly.

### Proposal
Perhaps the API should throw an error if `endHeight` is above what the node believes to be sealed head, instead of clamping it? For backwards compatibility could add a "strict mode" parameter or `getEventsAtBlockHeightRangeStrict` function to enable this behavior.
Or in case this is the expected behavior, add a note in the documentation, that this is an edge case that should be handled by the consumer.

It is not clear to new users that the access node is a sort of load-balancer, and that the results of `getBlock(true).height` might not be valid in sub-sequent calls. The error thrown when startHeight is out of bounds might also cause people to assume the same will happen if endHeight is oob.

Maybe the endpoint could return the actual block range that was queried, but that would be a breaking change.

### Code ref:
https://github.com/onflow/flow-go/blob/fc142de91ecdd3c12555cdc3f2e2a1a1773dfa1f/engine/access/rpc/backend/backend_events.go#L63

**Comment by peterargue** [comment] 2023-02-06 17:32
Hi @NtTestAlert thanks for the report. Looking over the details and code, it's definitely possible for blocks to be missed.

As you noted, this is ultimately caused by using the Access API TLS proxy (which is recommended) since you can't pin your requests to a single node. 

I opened an issue a little while back to add metadata about the node's state to address this across all endpoints: https://github.com/onflow/flow-go/issues/2906
There are also plans to create a streaming API for events (FLIP coming soon).

**Comment by peterargue** [comment] 2023-12-12 14:38
We've added 3 changes to address this issue:
1. Event streaming endpoints are now available for both REST and gRPC. This is the preferred way to query events over a large range of blocks
2. The REST API was updated to return a block events response for every block searched. You can now check the height from the last item in the response to find the last block searched.
3. A metadata field was added to grpc responses (including grpc-web) which includes the node's finalized block height. this can be used to detect if the height is less than the height from previous requests.

I'm going to close this issue out.

**Closed by peterargue** 2023-12-12 14:38 UTC
Labels: S-Access
